apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: civak2yd6-python 
  janus-idp.io/tekton: civak2yd6-python
  backstage.io/kubernetes-id: civak2yd6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: civak2yd6-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml