apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: civak2yd6-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: civak2yd6-python 
  name: civak2yd6-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: civak2yd6-python 
